<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE cvs [
	<!--
	param entity pour un type enumere
-->
	<!ENTITY % booleanType "(true|false)">
	<!ENTITY % etatCivil "nom, pnom, pnom?, pnom?">
	<!--
	section IDENT
-->
	<!ELEMENT nom (#PCDATA)>
	<!ELEMENT tel (#PCDATA)>
	<!ELEMENT mail (#PCDATA)>
	<!ELEMENT pnom (#PCDATA)>
	<!ELEMENT ident (nom, pnom, pnom?, pnom?, datenaiss, permis, langues, (tel | mail)?)>
	<!ELEMENT langue EMPTY>
	<!ATTLIST langue
		matern (true | false) #REQUIRED
		langName CDATA #REQUIRED
	>
	<!ELEMENT permis (#PCDATA)>
	<!ATTLIST permis
		ownVehicule (true | false) #REQUIRED
	>
	<!ELEMENT langues (langue+)>
	<!ELEMENT datenaiss (#PCDATA)>
	<!--
	ENTITIES
-->
	<!ENTITY euro "&#x20ac;">
	<!--ou #8364 en base 10-->
	<!ENTITY nbsp "&#160;">
	<!--ou #xA0 en base 16-->
	<!ENTITY signature "DESORBAIX Alexanrde">
	<!ELEMENT cv (ident, pretentionSalariale?, formations, experiences)>
	<!ATTLIST cv
		idcv ID #REQUIRED
	>
	<!ELEMENT pretentionSalariale (#PCDATA)>
	<!ELEMENT deb (#PCDATA)>
	<!ELEMENT fin (#PCDATA)>
	<!ELEMENT centre (#PCDATA)>
	<!ELEMENT diplome (intitule)>
	<!ATTLIST diplome
		obtenu (true | false) #IMPLIED
		noteS20 CDATA #IMPLIED
	>
	<!ELEMENT diplomes (diplome*)>
	<!ELEMENT intitule (#PCDATA)>
	<!ELEMENT formation (deb, fin?, centre, diplomes)>
	<!ELEMENT experience (deb, fin?, intitule)>
	<!ELEMENT formations (formation*)>
	<!ELEMENT experiences (experience*)>
	<!--
	ajout pour demo ref d'id
-->
	<!ELEMENT cvs (meilleurCV, cvSelectiones, cv+)>
	<!ELEMENT meilleurCV EMPTY>
	<!ATTLIST meilleurCV
		idcv IDREF #REQUIRED
	>
	<!ELEMENT cvSelectiones EMPTY>
	<!ATTLIST cvSelectiones
		idcvs IDREFS #REQUIRED
	>
]>
<cvs>
	<meilleurCV idcv="_234"/>
	<cvSelectiones idcvs="_234 _236"/>
	<cv idcv="_234">
		<ident>
			<nom>DESORBAIX</nom>
			<pnom>Alexandre</pnom>
			<pnom>Dominique</pnom>
			<pnom>joël</pnom>
			<datenaiss>1984-08-03</datenaiss>
			<permis ownVehicule="false">A</permis>
			<langues>
				<langue matern="true" langName="FR"/>
				<langue matern="false" langName="EN"/>
			</langues>
			<!--<tel>06.64.27.63.60</tel>-->
			<mail>desorbaix@free.fr</mail>
		</ident>
		<pretentionSalariale>10000&euro;</pretentionSalariale>
		<formations>
			<formation>
				<deb>2004</deb>
				<fin>2008</fin>
				<centre>Fac &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;de versailles</centre>
				<diplomes>
					<diplome obtenu="true" noteS20="25">
						<intitule>DUT GEII</intitule>
					</diplome>
					<diplome obtenu="false">
						<intitule>Doctorat informatique</intitule>
					</diplome>
				</diplomes>
			</formation>
			<formation>
				<deb>2021</deb>
				<centre>Orsys</centre>
				<diplomes>
					<diplome>
						<intitule>Programation XML &amp; dérivés</intitule>
					</diplome>
				</diplomes>
			</formation>
		</formations>
		<experiences>
			<experience>
				<deb>2004</deb>
				<fin>2008</fin>
				<intitule>SFC societe francaise de ceramique</intitule>
			</experience>
			<experience>
				<deb>2008</deb>
				<intitule>Formateur Orsys</intitule>
			</experience>
		</experiences>
	</cv>
	<cv idcv="_235">
		<ident>
			<nom>DESORBAIX</nom>
			<pnom>Alexandre</pnom>
			<pnom>Dominique</pnom>
			<pnom>joël</pnom>
			<datenaiss>1984-08-03</datenaiss>
			<permis ownVehicule="false">A</permis>
			<langues>
				<langue matern="true" langName="FR"/>
				<langue matern="false" langName="EN"/>
			</langues>
			<!--<tel>06.64.27.63.60</tel>-->
			<mail>desorbaix@free.fr</mail>
		</ident>
		<formations>
			<formation>
				<deb>2004</deb>
				<fin>2008</fin>
				<centre>Fac de versailles</centre>
				<diplomes>
					<diplome obtenu="true">
						<intitule>DUT GEII</intitule>
					</diplome>
					<diplome obtenu="false">
						<intitule>Doctorat informatique</intitule>
					</diplome>
				</diplomes>
			</formation>
			<formation>
				<deb>2021</deb>
				<centre>Orsys</centre>
				<diplomes>
					<diplome>
						<intitule>Programation XML + dérivés</intitule>
					</diplome>
				</diplomes>
			</formation>
		</formations>
		<experiences>
			<experience>
				<deb>2004</deb>
				<fin>2008</fin>
				<intitule>SFC societe francaise de ceramique</intitule>
			</experience>
			<experience>
				<deb>2008</deb>
				<intitule>Formateur Orsys</intitule>
			</experience>
		</experiences>
	</cv>
	<cv idcv="_236">
		<ident>
			<nom>DESORBAIX</nom>
			<pnom>Alexandre</pnom>
			<pnom>Dominique</pnom>
			<pnom>joël</pnom>
			<datenaiss>1984-08-03</datenaiss>
			<permis ownVehicule="false">A</permis>
			<langues>
				<langue matern="true" langName="FR"/>
				<langue matern="false" langName="EN"/>
			</langues>
			<!--<tel>06.64.27.63.60</tel>-->
			<mail>desorbaix@free.fr</mail>
		</ident>
		<formations>
			<formation>
				<deb>2004</deb>
				<fin>2008</fin>
				<centre>Fac de versailles</centre>
				<diplomes>
					<diplome obtenu="true">
						<intitule>DUT GEII</intitule>
					</diplome>
					<diplome obtenu="false">
						<intitule>Doctorat informatique</intitule>
					</diplome>
				</diplomes>
			</formation>
			<formation>
				<deb>2021</deb>
				<centre>Orsys</centre>
				<diplomes>
					<diplome>
						<intitule>Programation XML + dérivés</intitule>
					</diplome>
				</diplomes>
			</formation>
		</formations>
		<experiences>
			<experience>
				<deb>2004</deb>
				<fin>2008</fin>
				<intitule>SFC societe francaise de ceramique</intitule>
			</experience>
			<experience>
				<deb>2008</deb>
				<intitule>Formateur Orsys</intitule>
			</experience>
		</experiences>
	</cv>
</cvs>
